"""Reference-data seeding.

Idempotent: safe to run on every boot. Reads `app/data/tractates.json`, which
is generated by `scripts/fetch_tractates.py` from Sefaria and committed, so
seeding never depends on the network.

    .venv/Scripts/python.exe -m app.db.seed
"""

from __future__ import annotations

import json
import logging
import pathlib

from sqlalchemy import func, select
from sqlalchemy.orm import Session

from app.core.config import get_settings
from app.db.session import SessionLocal, engine
from app.models import Base, Mishnah, ShopItem, Tractate

logger = logging.getLogger(__name__)

DATA_FILE = pathlib.Path(__file__).parent.parent / "data" / "tractates.json"


def seed_tractates(session: Session) -> int:
    payload = json.loads(DATA_FILE.read_text(encoding="utf-8"))
    existing = {
        slug for (slug,) in session.execute(select(Tractate.slug)).all()
    }
    added = 0

    for entry in payload:
        if entry["slug"] in existing:
            continue

        tractate = Tractate(
            slug=entry["slug"],
            name_he=entry["name_he"],
            name_en=entry["name_en"],
            sefaria_title=entry.get("sefaria_title", f"Mishnah {entry['name_en']}"),
            seder=entry["seder"],
            order_index=entry["order_index"],
            chapter_count=entry["chapter_count"],
            mishnayot_count=entry["mishnayot_count"],
        )
        session.add(tractate)
        session.flush()

        # `ordinal` is a running 1-based index across the whole tractate, which
        # is what turns "where am I" into a single integer compare.
        ordinal = 0
        for chapter_no, chapter_len in enumerate(entry["chapter_lengths"] or [], 1):
            for mishnah_no in range(1, chapter_len + 1):
                ordinal += 1
                session.add(
                    Mishnah(
                        tractate_id=tractate.id,
                        chapter=chapter_no,
                        number=mishnah_no,
                        ordinal=ordinal,
                        sefaria_ref=(
                            f"{tractate.sefaria_title} {chapter_no}:{mishnah_no}"
                        ),
                    )
                )

        if ordinal and ordinal != tractate.mishnayot_count:
            raise ValueError(
                f"{entry['slug']}: generated {ordinal} mishnayot but the "
                f"tractate declares {tractate.mishnayot_count}"
            )
        added += 1

    return added


def seed_shop(session: Session) -> None:
    settings = get_settings()
    if session.get(ShopItem, "streak_freeze") is None:
        session.add(
            ShopItem(
                sku="streak_freeze",
                name_he="הקפאת רצף",
                description_he="מגינה על הרצף שלך ביום אחד שהוחמץ — בלי איבוד נקודות.",
                cost_points=settings.streak_freeze_cost,
                max_owned=3,
            )
        )


def run(create_tables: bool = True) -> dict:
    if create_tables:
        Base.metadata.create_all(engine)

    with SessionLocal() as session:
        added = seed_tractates(session)
        seed_shop(session)
        session.commit()

        totals = session.execute(
            select(func.count(Tractate.id), func.sum(Tractate.mishnayot_count))
        ).one()

    summary = {
        "tractates_added": added,
        "tractates_total": totals[0],
        "mishnayot_total": int(totals[1] or 0),
    }
    logger.info("seed complete %s", summary)
    return summary


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    print(run())
