"""Reference-data seeding.

Idempotent: safe to run on every boot. Reads `app/data/tractates.json`, which
is generated by `scripts/fetch_tractates.py` from Sefaria and committed, so
seeding never depends on the network.

    .venv/Scripts/python.exe -m app.db.seed
"""

from __future__ import annotations

import json
import logging
import pathlib

from sqlalchemy import func, insert, select
from sqlalchemy.orm import Session

from app.core.config import get_settings
from app.db.session import SessionLocal, engine
from app.models import Base, Mishnah, ShopItem, Tractate

logger = logging.getLogger(__name__)

DATA_FILE = pathlib.Path(__file__).parent.parent / "data" / "tractates.json"


def seed_tractates(session: Session) -> int:
    """Insert any tractate that is not already there.

    Two things matter here because this runs on the boot path, before uvicorn
    binds a port, against a database that is one network hop away:

    * **Bulk inserts.** 4,192 mishnayot added one ORM object at a time is 4,192
      chances to pay a round trip. A single `insert()` per tractate is 63
      statements instead, and turns a cold start that a health check can time
      out into a couple of seconds.
    * **A commit per tractate.** If the process is killed halfway - which is
      exactly what an impatient platform does to a slow first boot - one big
      transaction rolls back and the next attempt starts from nothing, forever.
      Committing as we go means every restart resumes.
    """
    payload = json.loads(DATA_FILE.read_text(encoding="utf-8"))
    existing = {
        slug for (slug,) in session.execute(select(Tractate.slug)).all()
    }
    added = 0

    for entry in payload:
        if entry["slug"] in existing:
            continue

        tractate = Tractate(
            slug=entry["slug"],
            name_he=entry["name_he"],
            name_en=entry["name_en"],
            sefaria_title=entry.get("sefaria_title", f"Mishnah {entry['name_en']}"),
            seder=entry["seder"],
            order_index=entry["order_index"],
            chapter_count=entry["chapter_count"],
            mishnayot_count=entry["mishnayot_count"],
        )
        session.add(tractate)
        session.flush()

        # `ordinal` is a running 1-based index across the whole tractate, which
        # is what turns "where am I" into a single integer compare.
        rows = []
        ordinal = 0
        for chapter_no, chapter_len in enumerate(entry["chapter_lengths"] or [], 1):
            for mishnah_no in range(1, chapter_len + 1):
                ordinal += 1
                rows.append(
                    {
                        "tractate_id": tractate.id,
                        "chapter": chapter_no,
                        "number": mishnah_no,
                        "ordinal": ordinal,
                        "sefaria_ref": (
                            f"{tractate.sefaria_title} {chapter_no}:{mishnah_no}"
                        ),
                    }
                )

        if ordinal and ordinal != tractate.mishnayot_count:
            raise ValueError(
                f"{entry['slug']}: generated {ordinal} mishnayot but the "
                f"tractate declares {tractate.mishnayot_count}"
            )
        if rows:
            session.execute(insert(Mishnah), rows)
        session.commit()
        added += 1

    return added


def seed_shop(session: Session) -> None:
    settings = get_settings()
    if session.get(ShopItem, "streak_freeze") is None:
        session.add(
            ShopItem(
                sku="streak_freeze",
                name_he="הקפאת רצף",
                description_he="מגינה על הרצף שלך ביום אחד שהוחמץ — בלי איבוד נקודות.",
                cost_points=settings.streak_freeze_cost,
                max_owned=3,
            )
        )


def run(create_tables: bool = True) -> dict:
    if create_tables:
        Base.metadata.create_all(engine)

    with SessionLocal() as session:
        added = seed_tractates(session)
        seed_shop(session)
        session.commit()

        totals = session.execute(
            select(func.count(Tractate.id), func.sum(Tractate.mishnayot_count))
        ).one()

    summary = {
        "tractates_added": added,
        "tractates_total": totals[0],
        "mishnayot_total": int(totals[1] or 0),
    }
    logger.info("seed complete %s", summary)
    return summary


if __name__ == "__main__":
    import sys

    logging.basicConfig(level=logging.INFO)
    # In production Alembic owns the schema, so the container seeds with
    # --no-create: create_all cannot express a migration, and letting both
    # tools define tables is how they drift apart.
    print(run(create_tables="--no-create" not in sys.argv))
