"""initial schema

Revision ID: 0bcb783ad057
Revises: 
Create Date: 2026-08-14 14:13:13.030658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0bcb783ad057'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('name_he', sa.String(length=120), nullable=False),
    sa.Column('description_he', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('points_reward', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('shop_items',
    sa.Column('sku', sa.String(length=48), nullable=False),
    sa.Column('name_he', sa.String(length=120), nullable=False),
    sa.Column('description_he', sa.Text(), nullable=True),
    sa.Column('cost_points', sa.Integer(), nullable=False),
    sa.Column('max_owned', sa.SmallInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('sku')
    )
    op.create_table('text_cache',
    sa.Column('ref', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('he_ref', sa.String(length=160), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('license', sa.String(length=64), nullable=True),
    sa.Column('version_title', sa.String(length=200), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('ref', 'kind')
    )
    op.create_table('tractates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name_he', sa.String(length=64), nullable=False),
    sa.Column('name_en', sa.String(length=64), nullable=False),
    sa.Column('sefaria_title', sa.String(length=96), nullable=False),
    sa.Column('seder', sa.String(length=32), nullable=False),
    sa.Column('order_index', sa.SmallInteger(), nullable=False),
    sa.Column('chapter_count', sa.SmallInteger(), nullable=False),
    sa.Column('mishnayot_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('google_sub', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('elevation_m', sa.Float(), nullable=False),
    sa.Column('in_israel', sa.Boolean(), nullable=False),
    sa.Column('candle_lighting_offset', sa.SmallInteger(), nullable=False),
    sa.Column('observes_shabbat', sa.Boolean(), nullable=False),
    sa.Column('observes_yom_tov', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_google_sub'), ['google_sub'], unique=True)

    op.create_table('freeze_usages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('covered_date', sa.Date(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'covered_date', name='uq_freeze_per_day')
    )
    op.create_table('mishnayot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tractate_id', sa.Integer(), nullable=False),
    sa.Column('chapter', sa.SmallInteger(), nullable=False),
    sa.Column('number', sa.SmallInteger(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('sefaria_ref', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['tractate_id'], ['tractates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tractate_id', 'chapter', 'number', name='uq_mishnah_addr'),
    sa.UniqueConstraint('tractate_id', 'ordinal', name='uq_mishnah_ordinal')
    )
    with op.batch_alter_table('mishnayot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mishnayot_tractate_id'), ['tractate_id'], unique=False)

    op.create_table('point_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('txn_type', sa.String(length=24), nullable=False),
    sa.Column('related_date', sa.Date(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=True),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('point_transactions', schema=None) as batch_op:
        batch_op.create_index('ix_txn_user_created', ['user_id', sa.literal_column('created_at DESC')], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_id', sa.Uuid(), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.ForeignKeyConstraint(['replaced_by_id'], ['refresh_tokens.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('shabbat_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('shabbat_date', sa.Date(), nullable=False),
    sa.Column('friday_date', sa.Date(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('earned_motash_bonus', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'shabbat_date', name='uq_shabbat_report')
    )
    op.create_table('study_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('tractate_id', sa.Integer(), nullable=False),
    sa.Column('daily_goal', sa.SmallInteger(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('estimated_end_date', sa.Date(), nullable=True),
    sa.Column('current_ordinal', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('daily_goal BETWEEN 1 AND 50', name='ck_goal_range'),
    sa.ForeignKeyConstraint(['tractate_id'], ['tractates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('study_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_plans_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_plans_user_id'), ['user_id'], unique=False)
        batch_op.create_index('uq_one_active_plan', ['user_id'], unique=True, postgresql_where=sa.text("status = 'active'"), sqlite_where=sa.text("status = 'active'"))

    op.create_table('user_achievements',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['code'], ['achievements.code'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'code')
    )
    op.create_table('user_inventory',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('sku', sa.String(length=48), nullable=False),
    sa.Column('quantity', sa.SmallInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='ck_inventory_non_negative'),
    sa.ForeignKeyConstraint(['sku'], ['shop_items.sku'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'sku')
    )
    op.create_table('user_stats',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('lifetime_points_earned', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_settled_date', sa.Date(), nullable=True),
    sa.Column('total_units_completed', sa.Integer(), nullable=False),
    sa.Column('freezes_consumed', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('current_streak >= 0', name='ck_streak_non_negative'),
    sa.CheckConstraint('total_points >= 0', name='ck_points_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('study_days',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('day_kind', sa.String(length=16), nullable=False),
    sa.Column('required_units', sa.SmallInteger(), nullable=False),
    sa.Column('completed_units', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('credit_source', sa.String(length=16), nullable=True),
    sa.Column('points_awarded', sa.Integer(), nullable=False),
    sa.Column('multiplier', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('streak_after', sa.Integer(), nullable=True),
    sa.Column('first_logged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('completed_units >= 0', name='ck_units_non_negative'),
    sa.ForeignKeyConstraint(['plan_id'], ['study_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'local_date', name='uq_user_day')
    )
    with op.batch_alter_table('study_days', schema=None) as batch_op:
        batch_op.create_index('ix_days_open', ['user_id', 'local_date'], unique=False, postgresql_where=sa.text("status IN ('pending', 'shabbat_pending')"), sqlite_where=sa.text("status IN ('pending', 'shabbat_pending')"))
        batch_op.create_index('ix_days_user_date_desc', ['user_id', sa.literal_column('local_date DESC')], unique=False)

    op.create_table('study_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('credited_local_date', sa.Date(), nullable=False),
    sa.Column('units', sa.SmallInteger(), nullable=False),
    sa.Column('from_ordinal', sa.Integer(), nullable=False),
    sa.Column('to_ordinal', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['study_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('study_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_events_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_events_user_id'))

    op.drop_table('study_events')
    with op.batch_alter_table('study_days', schema=None) as batch_op:
        batch_op.drop_index('ix_days_user_date_desc')
        batch_op.drop_index('ix_days_open', postgresql_where=sa.text("status IN ('pending', 'shabbat_pending')"), sqlite_where=sa.text("status IN ('pending', 'shabbat_pending')"))

    op.drop_table('study_days')
    op.drop_table('user_stats')
    op.drop_table('user_inventory')
    op.drop_table('user_achievements')
    with op.batch_alter_table('study_plans', schema=None) as batch_op:
        batch_op.drop_index('uq_one_active_plan', postgresql_where=sa.text("status = 'active'"), sqlite_where=sa.text("status = 'active'"))
        batch_op.drop_index(batch_op.f('ix_study_plans_user_id'))
        batch_op.drop_index(batch_op.f('ix_study_plans_status'))

    op.drop_table('study_plans')
    op.drop_table('shabbat_reports')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('point_transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_txn_user_created')

    op.drop_table('point_transactions')
    with op.batch_alter_table('mishnayot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mishnayot_tractate_id'))

    op.drop_table('mishnayot')
    op.drop_table('freeze_usages')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_google_sub'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('tractates')
    op.drop_table('text_cache')
    op.drop_table('shop_items')
    op.drop_table('achievements')
    # ### end Alembic commands ###
